### ISSUE TITLE
Why 2 dependencies?

### ISSUE THREAD

**Issue by tererecool** [jraska/Falcon#12]
Could you please explain why following 2 additions are necessary?:

compile 'com.jraska:falcon:1.0.3'
androidTestCompile 'com.jraska:falcon-spoon-compat:1.0.3'

What's the difference between both?

**Comment by jraska** [comment]
Hi,

'com.jraska:falcon:1.0.3' dependency contains Falcon class itself without any dependencies.

'com.jraska:falcon-spoon-compat:1.0.3' contains FalconSpoon class and also dependency to Spoon.

That means when you include the falcon dependency, you can already take screenshots without any other dependency and when you include spoon-compat dependency, you can use Falcon with Spoon together, but you are also adding Spoon into your project.

compile and androidTestCompile are just examples of usage.
compile for Falcon, because you may use it anywhere in your app and androidTestCompile was used for spoon-compat, because Spoon is intended to use for instrumented tests on device
