### ISSUE TITLE
sluggish issue in case of scrolling.

### ISSUE THREAD

**Issue by vikash1711** [jraska/Falcon#16]
I was using this code.
I am facing sluggish issue while taking the screenshots during scrolling. Just a little discontinuity, so no smooth scrolling. 
I tried debugging, and I narrowed down which part of the code is giving this, where we are posting a task on UiThread to capture screenshots and overlap in the case of multiple views.
activity.runOnUiThread(new Runnable() {
        @Override
        public void run() {
          try {
            drawRootsToBitmap(viewRoots, bitmap);
          } finally {
            latch.countDown();
          }
        }
      });

      latch.await();
    }

But I did not found any solution.
Can you help me out to make it smooth?

**Comment by jraska** [comment]
Hi, thank you for using Falcon library and your question.

I'm afraid I cannot do anything with this. There is basically only drawing Views to Bitmap Canvas, which is expensive, because it needs to set milions of values in Bitmap array. 

I'm not aware about any technique how to make it faster so it will always take some time to take screenshot.
