### ISSUE TITLE
Does not work when the activity contains mapview

### ISSUE THREAD

**Issue by futhrevo** [jraska/Falcon#24]
If there is a mapview in the layout it is being rendered as black solid with only Google logo on it.

**Comment by jraska** [comment]
Hi,

Unfortunately, GoogleMap uses OpenGL layer and we don't have access to it, therefore it is not possible to draw its content through View objects, which we use so that is the reason why.

I will be happy for any solution to this problem, because you are not the only one having that problem: #1 .
